/* Plugin Template generated by Pawn Studio */

/*
* Color Table
\x01 = Normal (White)
\x02 = None (White)
\x03 = Light green
\x04 = Green
\x05 = Olive
\x06 = black  (Yellow X)
*/
#include <sourcemod>

#define Plugin_Version "1.0"
new Handle:g_CvarEnabled = INVALID_HANDLE;

public Plugin:myinfo = 
{
	name = "Dead Report",
	author = "naong",
	description ="Reports player's death.",
	version = Plugin_Version,
	url = "http://teampl.mooo.com:50000"
}

public OnPluginStart()
{
	g_CvarEnabled = CreateConVar("sm_deadreport_enabled","1","Enables(1) or disables(0) the plugin.",FCVAR_NOTIFY);
	HookEvent("player_death", Event_PlayerDeath, EventHookMode_PostNoCopy);
}

public OnPluginEnd()
{
	UnhookEvent("player_death", Event_PlayerDeath);
}

public Event_PlayerDeath(Handle:event, const String:name[], bool:dontBroadcast)
{
	if (!GetConVarBool(g_CvarEnabled)) return;
	
	new iVictim = GetClientOfUserId(GetEventInt(event, "userid"));
	
	if(!IsFakeClient(iVictim)) {
		new iKiller = GetClientOfUserId(GetEventInt(event, "attacker"));
		
		new String:sWeaponName[32];
		GetEventString(event, "weapon", sWeaponName, sizeof(sWeaponName));
		
		PrintToChatAll("\x03%N\x01 is killed by \x05%N (%s)", iVictim, iKiller, sWeaponName);
	}
}